# Generated by Django 3.0.11 on 2021-04-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210331_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
