# Generated by Django 3.0.11 on 2021-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='limit_date',
            field=models.DateTimeField(),
        ),
    ]
