# Generated by Django 3.0.11 on 2021-04-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
