# Generated by Django 3.0.11 on 2021-04-05 19:16

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='null', upload_to='tag_image', verbose_name='Tag Image'),
        ),
    ]
