# Generated by Django 3.0.11 on 2021-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_status',
            field=models.CharField(default='not_notified', max_length=64),
        ),
    ]
