# Generated by Django 3.0.11 on 2021-08-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='limit_date',
            field=models.DateTimeField(verbose_name='Fecha Limite'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default='null', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notification_status',
            field=models.CharField(choices=[('notified', 'notificado'), ('not_notified', 'no notificado')], default='not_notified', max_length=64),
        ),
    ]
