# Generated by Django 3.0.11 on 2022-02-18 13:37

import compras.orders.models
import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20220124_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_place',
            field=models.CharField(default='null', max_length=100, verbose_name='Lugar de Entrega'),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, default=compras.orders.models.next_year, verbose_name='Horario de Entrega'),
        ),
        migrations.AddField(
            model_name='listingproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
