# Generated by Django 3.0.11 on 2022-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
